//Esse método não trava o código, apenas absorve o erro e imprime na tela

//let b = 2

try {
    let a = 2 + b;
} catch(e) {
    console.log(e)
}

console.log('teste')
